// Starter word list — all exactly 7 letters, all uppercase.
// Expand this list before production.
export const WORD_LIST: string[] = [
  'ABSENCE', 'ANCIENT', 'BALANCE', 'CABINET', 'CAPTAIN',
  'CHAPTER', 'CLIMATE', 'COLLEGE', 'CONTAIN', 'COUNCIL',
  'COUNTRY', 'COURAGE', 'CURRENT', 'DELIGHT', 'DOLPHIN',
  'EASTERN', 'FANTASY', 'FARMING', 'FEELING', 'FORWARD',
  'FREEDOM', 'GARBAGE', 'GENERAL', 'GENUINE', 'GROWING',
  'HARMONY', 'HARVEST', 'HISTORY', 'HOLIDAY', 'HUNDRED',
  'IMAGINE', 'INCLUDE', 'KITCHEN', 'LANDING', 'LANTERN',
  'LARGEST', 'LEAVING', 'LIMITED', 'MARRIED', 'MORNING',
  'NOTHING', 'OPINION', 'OUTSIDE', 'PATTERN', 'PICTURE',
  'PLAYING', 'PRESENT', 'PROBLEM', 'PROJECT', 'QUARTER',
  'QUICKLY', 'REMAINS', 'REPLACE', 'RESULTS', 'SCIENCE',
  'SILENCE', 'SOCIETY', 'SOMEONE', 'SPECIAL', 'STRANGE',
  'STUDENT', 'SUCCESS', 'SUGGEST', 'SUPPORT', 'SYSTEMS',
  'TEACHER', 'TESTING', 'TONIGHT', 'TROUBLE', 'UNIFORM',
  'UNKNOWN', 'USUALLY', 'VALLEYS', 'VARIOUS', 'VENTURE',
  'VIBRANT', 'VIRTUAL', 'WESTERN', 'WHETHER', 'WITHOUT',
  'WRITING', 'YOUNGER',
];
